[build]
  command = "NEXT_DISABLE_STATIC_OPTIMIZATION=true npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.10.0"

# Remove the NextJS plugin since we're using static export
# [[plugins]]
#  package = "@netlify/plugin-nextjs"

# Remove functions section since we're using static export
# [functions]
#  included_files = [".next/server/**"]
#  node_bundler = "esbuild" 