[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.10.0"
  # Ensure no server-side rendering is attempted
  NEXT_TELEMETRY_DISABLED = "1"

# Remove the NextJS plugin since we're using static export
# [[plugins]]
#  package = "@netlify/plugin-nextjs"

# Remove functions section since we're using static export
# [functions]
#  included_files = [".next/server/**"]
#  node_bundler = "esbuild"

# Add redirects for SPA navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 